"""login lockout tracking

Revision ID: 7ee5a3c6b1b7
Revises: 149ab81971cb
Create Date: 2026-09-17 12:21:40.534659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee5a3c6b1b7'
down_revision: Union[str, None] = '149ab81971cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows - SQLite rejects a NOT NULL
    # ADD COLUMN with no default on a non-empty table, and this can run
    # against a database that already has real users in it.
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    # ### end Alembic commands ###
